#compile only cuda files into all the given subdirs

#list of sub folder to compile
ALL_SUB_DIRS = 	filter_color_conv\
		gradients_edges_corners\
		histograms
#\
		morpho_op

		#add sub folders here

#update the path to gpucv root folder
ROOTDIR = ../../../../
include $(ROOTDIR)etc/cuda_common_subdirs.mk

