#compile only cuda files into all the given subdirs

#list of sub folder to compile
ALL_SUB_DIRS = 	image_processing
		#\
		pattern_recognition
		#add sub folders here

#update the path to gpucv root folder
ROOTDIR = ../../../
SHARED_LIB_TEMP = cvgcu
include $(ROOTDIR)etc/cuda_common_subdirs.mk

