#compile only cuda files into all the given subdirs

#list of sub folder to compile
ALL_SUB_DIRS = 	arithm_logic\
		discrete_transforms\
		linear_algebra\
		math\
		statistics\
		transform_permut\
		copy_fill
		#add sub folders here

#update the path to gpucv root folder
ROOTDIR = ../../../../
include $(ROOTDIR)etc/cuda_common_subdirs.mk

