#compile only cuda files into all the given subdirs

#list of sub folder to compile
ALL_SUB_DIRS = 	oper_array
		#add sub folders here

#update the path to gpucv root folder
ROOTDIR = ../../../
export SHARED_LIB_TMP = cxcoregcu
include $(ROOTDIR)etc/cuda_common_subdirs.mk



